(function(){
  async function getPatient(patientId){
    const {data,error}=await Clinic.sb.from('patients').select('*').eq('id',patientId).single();
    if(error) throw error; return data;
  }

  async function getQueue(){
    const C=Clinic,today=C.cairoDate(),start=`${today}T00:00:00+03:00`,end=`${today}T23:59:59+03:00`;
    const {data,error}=await C.sb.from('appointments').select('*').eq('doctor_id',C.user.id).eq('status','waiting').gte('scheduled_start',start).lte('scheduled_start',end).order('sent_to_doctor_at',{ascending:true});
    if(error)throw error;return data||[];
  }

  window.ClinicPages['queue']=async function(){
    const C=Clinic;C.setTitle(C.t('queue'));const q=await getQueue();const ids=[...new Set(q.map(x=>x.patient_id))];const {data:pts}=ids.length?await C.sb.from('patients').select('id,medical_record_number,english_name,arabic_name,birth_year,date_of_birth,gender').in('id',ids):{data:[]};const pm=new Map((pts||[]).map(p=>[p.id,p]));
    document.getElementById('mainContent').innerHTML=`<section class="page-toolbar"><div><span class="eyebrow">LIVE QUEUE</span><h2>${C.lang==='ar'?'قائمة الانتظار':'My Queue'}</h2><p class="muted">${q.length} ${C.lang==='ar'?'مريض في الانتظار':'patient(s) waiting'}</p></div><button id="refreshQueue" class="secondary-button">${C.lang==='ar'?'تحديث':'Refresh'}</button></section><section class="queue-cards">${q.length?q.map(a=>{const p=pm.get(a.patient_id)||{};const since=a.sent_to_doctor_at?Math.max(0,Math.floor((Date.now()-new Date(a.sent_to_doctor_at))/60000)):0;return`<article class="queue-card"><div class="queue-card-top"><div><span class="eyebrow">${C.escape(p.medical_record_number||'')}</span><h3>${C.escape(p.english_name||p.arabic_name||'Patient')}</h3><p class="muted">${C.ageFromBirthYear(p.birth_year,p.date_of_birth)} ${C.lang==='ar'?'سنة':'y'} • ${C.escape(p.gender||'—')}</p></div><div class="wait-badge">${since} min</div></div><button class="primary-button compact" data-start-consultation="${a.id}">${C.lang==='ar'?'بدء الكشف':'Start Consultation'}</button></article>`}).join(''):`<div class="content-card empty-state">${C.lang==='ar'?'لا يوجد مرضى في الانتظار حالياً.':'No patients are waiting right now.'}</div>`}</section>`;
    document.getElementById('refreshQueue').onclick=()=>C.route('queue');
    document.querySelectorAll('[data-start-consultation]').forEach(b=>b.onclick=async()=>{const id=b.dataset.startConsultation;const {error}=await C.sb.rpc('frontend_start_consultation',{p_id:id});if(error)return C.toast(error.message,'error');const {data:visit,error:ve}=await C.sb.rpc('frontend_open_clinical_visit',{p_appointment:id});if(ve)return C.toast(ve.message,'error');const v=Array.isArray(visit)?visit[0]:visit;C.route('clinical-visit',{visitId:v.id||v.visit_id,appointmentId:id});});
  };

  async function loadStructured(visitId){
    const C=Clinic;const [d,i,m]=await Promise.all([
      C.sb.from('visit_diagnoses').select('*').eq('visit_id',visitId).order('created_at'),
      C.sb.from('investigation_orders').select('*').eq('visit_id',visitId).order('created_at'),
      C.sb.from('visit_prescriptions').select('*').eq('visit_id',visitId).order('created_at')
    ]);return {diagnoses:d.data||[],investigations:i.data||[],medications:m.data||[]};
  }

  window.ClinicPages['clinical-visit']=async function({visitId,appointmentId=null,readOnly=false}){
    const C=Clinic;C.setLoading();
    const {data:visit,error}=await C.sb.from('clinical_visits').select('*').eq('id',visitId).single();if(error)return C.toast(error.message,'error');
    const patient=await getPatient(visit.patient_id);const structured=await loadStructured(visitId);const finalized=!!visit.finalized_at;const canEdit=!readOnly&&!finalized&&visit.doctor_id===C.user.id;
    let appt=appointmentId?null:null;if(visit.appointment_id){const r=await C.sb.from('appointments').select('*').eq('id',visit.appointment_id).single();appt=r.data;}
    C.setTitle(C.lang==='ar'?'الكشف الطبي':'Consultation');
    document.getElementById('mainContent').innerHTML=`
      <section class="consult-layout">
        <aside class="patient-side content-card"><span class="eyebrow">${C.escape(patient.medical_record_number)}</span><h2>${C.escape(patient.english_name||patient.arabic_name||'Patient')}</h2><div class="patient-side-meta"><span>${C.ageFromBirthYear(patient.birth_year,patient.date_of_birth)} ${C.lang==='ar'?'سنة':'years'}</span><span>${C.escape(patient.gender||'—')}</span><span>${C.escape(patient.mobile||'—')}</span></div><hr><div><span class="field-label">${C.lang==='ar'?'الحالة':'Visit status'}</span>${finalized?C.statusPill('finalized'):C.statusPill('draft')}</div>${finalized?`<p class="small-note">${C.lang==='ar'?'تم قفل السجل. أي إضافة لاحقة يجب أن تكون كتعديل موثق.':'Record is locked. Later changes must be added as an amendment.'}</p>`:''}</aside>
        <section class="consult-main">
          <form id="clinicalForm" class="content-card clinical-form">
            <div class="section-head"><div><span class="eyebrow">CLINICAL NOTE</span><h3>${C.lang==='ar'?'الزيارة الطبية':'Clinical visit'}</h3></div>${canEdit?`<button class="secondary-button" type="button" id="saveDraft">${C.lang==='ar'?'حفظ المسودة':'Save Draft'}</button>`:''}</div>
            ${['chief_complaint','history_present_illness','past_medical_history','family_history','social_history','allergies','current_medications','examination','diagnosis_summary','workup_plan','treatment_plan','clinical_notes','follow_up_plan'].map(key=>`<label class="clinical-field"><span>${key.replaceAll('_',' ')}</span><textarea name="${key}" class="control" ${canEdit?'':'disabled'}>${C.escape(visit[key]||'')}</textarea></label>`).join('')}
            <div class="clinical-vitals"><h4>Vitals</h4><div class="form-grid compact-grid">${[['systolic_bp','SBP'],['diastolic_bp','DBP'],['heart_rate','HR'],['respiratory_rate','RR'],['oxygen_saturation','SpO₂'],['temperature_c','Temp °C'],['weight_kg','Weight kg'],['height_cm','Height cm'],['random_glucose_mg_dl','Random glucose']].map(([k,l])=>`<label>${l}<input name="v_${k}" type="number" step="any" class="control" ${canEdit?'':'disabled'}></label>`).join('')}</div></div>
          </form>
          <section class="content-card"><div class="section-head"><h3>${C.lang==='ar'?'التشخيصات':'Diagnoses'}</h3>${canEdit?`<button class="table-action" id="addDiagnosis">+ Add</button>`:''}</div><div id="diagnosisList" class="chips-list">${structured.diagnoses.length?structured.diagnoses.map(d=>`<span class="info-chip"><strong>${C.escape(d.diagnosis_text)}</strong><small>${C.escape(d.classification||'')}</small></span>`).join(''):`<span class="muted">—</span>`}</div></section>
          <section class="content-card"><div class="section-head"><h3>${C.lang==='ar'?'الفحوصات المطلوبة':'Investigations'}</h3>${canEdit?`<button class="table-action" id="addInvestigation">+ Add</button>`:''}</div><div class="stack-list">${structured.investigations.length?structured.investigations.map(i=>`<article class="list-card"><div><div class="list-title">${C.escape(i.investigation_name)}</div><div class="muted">${C.escape(i.priority||'routine')}</div></div></article>`).join(''):`<span class="muted">—</span>`}</div></section>
          <section class="content-card"><div class="section-head"><h3>${C.lang==='ar'?'الروشتة':'Prescription'}</h3>${canEdit?`<button class="table-action" id="addMedication">+ Add</button>`:''}</div><div class="stack-list">${structured.medications.length?structured.medications.map(m=>`<article class="list-card"><div><div class="list-title">${C.escape(m.medication_name)} ${C.escape(m.strength||'')}</div><div class="muted">${C.escape([m.dose,m.route,m.frequency,m.duration].filter(Boolean).join(' • '))}</div></div></article>`).join(''):`<span class="muted">—</span>`}</div></section>
          <section class="content-card"><div class="consult-actions">${canEdit?`<button id="uploadClinicalDocument" class="secondary-button">📎 ${C.lang==='ar'?'رفع مستند':'Upload document'}</button><button id="referFromVisit" class="secondary-button">⇄ ${C.lang==='ar'?'تحويل المريض':'Refer patient'}</button><button id="finalizeVisit" class="danger-button">✓ ${C.lang==='ar'?'اعتماد وقفل الزيارة':'Finalize Visit'}</button>`:''}${finalized&&visit.doctor_id===C.user.id?`<button id="addAmendment" class="secondary-button">+ ${C.lang==='ar'?'إضافة تعديل':'Add Amendment'}</button>${appt?.status==='with_doctor'?`<button id="completeConsultation" class="primary-button compact">${C.lang==='ar'?'إنهاء الكشف':'Complete Consultation'}</button>`:''}`:''}</div></section>
        </section>
      </section>`;

    if(canEdit){
      document.getElementById('saveDraft').onclick=async()=>{
        const f=new FormData(document.getElementById('clinicalForm'));const payload={};['chief_complaint','history_present_illness','past_medical_history','family_history','social_history','allergies','current_medications','examination','diagnosis_summary','workup_plan','treatment_plan','clinical_notes','follow_up_plan'].forEach(k=>payload[k]=f.get(k)||null);
        const vitals={};['systolic_bp','diastolic_bp','heart_rate','respiratory_rate','oxygen_saturation','temperature_c','weight_kg','height_cm','random_glucose_mg_dl'].forEach(k=>{const v=f.get(`v_${k}`);if(v!=='')vitals[k]=Number(v);});if(Object.keys(vitals).length)payload.vitals=vitals;
        const {error}=await C.sb.rpc('frontend_save_clinical_visit',{p_visit:visitId,p_payload:payload});if(error)return C.toast(error.message,'error');C.toast(C.lang==='ar'?'تم حفظ المسودة':'Draft saved');
      };
      document.getElementById('addDiagnosis').onclick=()=>C.showModal({title:'Add diagnosis',body:`<form id="diagForm" class="form-grid"><label class="full-span">Diagnosis<input name="diagnosis_text" class="control" required></label><label>Classification<select name="classification" class="control"><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="differential">Differential</option></select></label><label>ICD-10<input name="diagnosis_code" class="control"></label><div class="form-actions full-span"><button class="primary-button compact">Add</button></div></form>`,onOpen:r=>r.querySelector('#diagForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await C.sb.from('visit_diagnoses').insert({visit_id:visitId,diagnosis_text:f.get('diagnosis_text'),classification:f.get('classification'),diagnosis_code:f.get('diagnosis_code')||null});if(error)return C.toast(error.message,'error');C.closeModal();C.route('clinical-visit',{visitId});}});
      document.getElementById('addInvestigation').onclick=()=>C.showModal({title:'Add investigation',body:`<form id="invForm" class="form-grid"><label class="full-span">Investigation<input name="investigation_name" class="control" required></label><label>Priority<select name="priority" class="control"><option value="routine">Routine</option><option value="urgent">Urgent</option></select></label><label>Category<input name="category" class="control"></label><label class="full-span">Clinical question<textarea name="clinical_question" class="control"></textarea></label><div class="form-actions full-span"><button class="primary-button compact">Add</button></div></form>`,onOpen:r=>r.querySelector('#invForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await C.sb.from('investigation_orders').insert({visit_id:visitId,investigation_name:f.get('investigation_name'),priority:f.get('priority'),category:f.get('category')||null,clinical_question:f.get('clinical_question')||null});if(error)return C.toast(error.message,'error');C.closeModal();C.route('clinical-visit',{visitId});}});
      document.getElementById('addMedication').onclick=()=>C.showModal({title:'Add medication',body:`<form id="medForm" class="form-grid"><label class="full-span">Medication<input name="medication_name" class="control" required></label><label>Strength<input name="strength" class="control"></label><label>Dose<input name="dose" class="control"></label><label>Route<input name="route" class="control"></label><label>Frequency<input name="frequency" class="control"></label><label>Duration<input name="duration" class="control"></label><label class="full-span">Instructions<textarea name="instructions" class="control"></textarea></label><div class="form-actions full-span"><button class="primary-button compact">Add</button></div></form>`,onOpen:r=>r.querySelector('#medForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await C.sb.from('visit_prescriptions').insert({visit_id:visitId,medication_name:f.get('medication_name'),strength:f.get('strength')||null,dose:f.get('dose')||null,route:f.get('route')||null,frequency:f.get('frequency')||null,duration:f.get('duration')||null,instructions:f.get('instructions')||null});if(error)return C.toast(error.message,'error');C.closeModal();C.route('clinical-visit',{visitId});}});
      document.getElementById('uploadClinicalDocument').onclick=()=>C.showModal({title:C.lang==='ar'?'رفع مستند طبي':'Upload clinical document',body:`<form id="docForm" class="form-grid"><label class="full-span">File<input name="file" type="file" class="control" required></label><label>Document type<input name="document_type" class="control" placeholder="Lab / Imaging / Other"></label><label class="full-span">Notes<textarea name="notes" class="control"></textarea></label><div class="form-actions full-span"><button class="primary-button compact">Upload</button></div></form>`,onOpen:r=>r.querySelector('#docForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file');if(!file?.name)return;const safeName=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,path=`${C.user.id}/${visitId}/${safeName}`;const up=await C.sb.storage.from('clinical-documents').upload(path,file,{upsert:false});if(up.error)return C.toast(up.error.message,'error');const reg=await C.sb.rpc('frontend_register_clinical_document',{p_visit:visitId,p_path:path,p_filename:file.name,p_mime:file.type||null,p_bytes:file.size,p_type:f.get('document_type')||null,p_note:f.get('notes')||null,p_result:null});if(reg.error)return C.toast(reg.error.message,'error');C.closeModal();C.toast(C.lang==='ar'?'تم رفع المستند':'Document uploaded');}});
      document.getElementById('referFromVisit').onclick=()=>Clinic.showReferralModal?.({visitId,patientId:visit.patient_id});
      document.getElementById('finalizeVisit').onclick=async()=>{if(!confirm(C.lang==='ar'?'بعد الاعتماد لن يمكن تعديل السجل مباشرة. متابعة؟':'After finalization the record cannot be directly edited. Continue?'))return;const {error}=await C.sb.rpc('frontend_finalize_clinical_visit',{p_visit:visitId});if(error)return C.toast(error.message,'error');C.toast(C.lang==='ar'?'تم اعتماد الزيارة':'Visit finalized');C.route('clinical-visit',{visitId});};
    }
    if(finalized&&visit.doctor_id===C.user.id){
      document.getElementById('addAmendment')&&(document.getElementById('addAmendment').onclick=()=>C.showModal({title:C.lang==='ar'?'إضافة تعديل موثق':'Add amendment',body:`<form id="amendForm"><textarea id="amendText" class="control" rows="7" required></textarea><div class="form-actions"><button class="primary-button compact">Save</button></div></form>`,onOpen:r=>r.querySelector('#amendForm').onsubmit=async e=>{e.preventDefault();const text=r.querySelector('#amendText').value.trim();if(!text)return;const {error}=await C.sb.rpc('frontend_add_clinical_amendment',{p_visit:visitId,p_text:text});if(error)return C.toast(error.message,'error');C.closeModal();C.toast('Amendment added');}}));
      document.getElementById('completeConsultation')&&(document.getElementById('completeConsultation').onclick=async()=>{const {error}=await C.sb.rpc('frontend_complete_consultation',{p_id:visit.appointment_id});if(error)return C.toast(error.message,'error');C.toast(C.lang==='ar'?'تم إنهاء الكشف':'Consultation completed');C.route('today-clinic');window.ClinicNotifications?.refresh?.();});
    }
  };
})();
