(function(){
  Clinic.showReferralModal = async function({visitId,patientId}){
    const C=Clinic;await C.loadDoctors(true);const targets=C.doctors.filter(d=>d.id!==C.user.id);
    if(!targets.length)return C.toast(C.lang==='ar'?'لا يوجد طبيب آخر متاح للتحويل.':'No other active doctor is available.','error');
    C.showModal({title:C.lang==='ar'?'تحويل المريض':'Refer patient',body:`<form id="referralForm" class="form-grid">
      <label class="full-span">${C.lang==='ar'?'إلى الطبيب':'To doctor'}<select name="to_doctor_id" class="control" required>${targets.map(d=>`<option value="${d.id}">${C.escape(d.display_name||d.username)}</option>`).join('')}</select></label>
      <label>${C.lang==='ar'?'الأولوية':'Urgency'}<select name="urgency" class="control"><option value="routine">Routine</option><option value="urgent">Urgent</option></select></label>
      <label class="full-span">${C.lang==='ar'?'سبب التحويل':'Referral reason'}<textarea name="referral_reason" class="control" required></textarea></label>
      <label class="full-span">${C.lang==='ar'?'السؤال الطبي':'Clinical question'}<textarea name="clinical_question" class="control"></textarea></label>
      <label class="full-span">${C.lang==='ar'?'ملاحظة إضافية':'Additional note'}<textarea name="referral_note" class="control"></textarea></label>
      <div class="form-actions full-span"><button class="primary-button compact">${C.lang==='ar'?'إرسال التحويل':'Send referral'}</button></div>
    </form>`,onOpen:r=>r.querySelector('#referralForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await C.sb.rpc('frontend_create_referral',{p_visit:visitId,p_to_doctor:f.get('to_doctor_id'),p_reason:f.get('referral_reason'),p_urgency:f.get('urgency'),p_question:f.get('clinical_question')||null,p_note:f.get('referral_note')||null});if(error)return C.toast(error.message,'error');C.closeModal();C.toast(C.lang==='ar'?'تم إرسال التحويل':'Referral sent');window.ClinicNotifications?.refresh?.();}});
  };

  async function patientMap(refs){
    const ids=[...new Set(refs.map(r=>r.patient_id).filter(Boolean))];if(!ids.length)return new Map();const {data}=await Clinic.sb.from('patients').select('id,medical_record_number,english_name,arabic_name').in('id',ids);return new Map((data||[]).map(p=>[p.id,p]));
  }

  async function doctorMap(refs){
    await Clinic.loadDoctors(true);return new Map(Clinic.doctors.map(d=>[d.id,d]));
  }

  window.ClinicPages['referrals']=async function(){
    const C=Clinic;C.setTitle(C.t('referrals'));
    const {data,error}=await C.sb.from('referrals').select('*').order('created_at',{ascending:false}).limit(100);if(error)return C.toast(error.message,'error');const refs=data||[],pm=await patientMap(refs),dm=await doctorMap(refs);
    document.getElementById('mainContent').innerHTML=`<section class="page-toolbar"><div><span class="eyebrow">CARE COORDINATION</span><h2>${C.lang==='ar'?'التحويلات':'Referrals'}</h2><p class="muted">${C.lang==='ar'?'التحويلات المرسلة والمستلمة.':'Incoming and outgoing referrals.'}</p></div></section>
      <div class="tabs" id="refTabs"><button class="tab active" data-mode="incoming">${C.lang==='ar'?'واردة':'Incoming'}</button><button class="tab" data-mode="outgoing">${C.lang==='ar'?'صادرة':'Outgoing'}</button><button class="tab" data-mode="all">${C.lang==='ar'?'الكل':'All'}</button></div><section id="refArea" class="content-card"></section>`;
    function render(mode){const rows=refs.filter(r=>mode==='all'||(mode==='incoming'?r.to_doctor_id===C.user.id:r.from_doctor_id===C.user.id));const area=document.getElementById('refArea');area.innerHTML=rows.length?`<div class="stack-list">${rows.map(r=>{const p=pm.get(r.patient_id)||{},from=dm.get(r.from_doctor_id)||{},to=dm.get(r.to_doctor_id)||{},incoming=r.to_doctor_id===C.user.id;return`<article class="referral-card ${r.urgency==='urgent'?'urgent':''}"><div class="referral-main"><div class="referral-topline"><span class="eyebrow">${C.escape(r.urgency)}</span>${C.statusPill(r.status)}</div><h3>${C.escape(p.english_name||p.arabic_name||'Patient')}</h3><p class="muted">${C.escape(p.medical_record_number||'')} • ${incoming?(C.lang==='ar'?'من':'From'):(C.lang==='ar'?'إلى':'To')}: ${C.escape((incoming?from:to).display_name||'Doctor')}</p><p>${C.escape(r.referral_reason)}</p>${r.clinical_question?`<div class="callout"><strong>${C.lang==='ar'?'السؤال الطبي':'Clinical question'}</strong><span>${C.escape(r.clinical_question)}</span></div>`:''}</div><div class="referral-actions"><button class="table-action" data-review-ref="${r.id}">${C.lang==='ar'?'فتح':'Review'}</button>${incoming&&r.status==='pending'?`<button class="table-action success-outline" data-ref-action="accept" data-id="${r.id}">Accept</button><button class="table-action danger-outline" data-ref-action="reject" data-id="${r.id}">Reject</button>`:''}${incoming&&r.status==='accepted'?`<button class="table-action success-outline" data-ref-action="start" data-id="${r.id}">Start</button>`:''}${incoming&&['accepted','in_progress'].includes(r.status)?`<button class="table-action" data-ref-action="complete" data-id="${r.id}">Complete</button>`:''}</div></article>`}).join('')}</div>`:`<div class="empty-state">${C.t('noData')}</div>`;
      area.querySelectorAll('[data-review-ref]').forEach(b=>b.onclick=()=>showReferral(refs.find(r=>r.id===b.dataset.reviewRef),pm,dm));area.querySelectorAll('[data-ref-action]').forEach(b=>b.onclick=()=>doAction(b.dataset.id,b.dataset.refAction));}
    document.querySelectorAll('#refTabs .tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('#refTabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.mode);});render('incoming');
  };

  async function doAction(id,act){
    const C=Clinic;let res;if(act==='accept')res=await C.sb.rpc('frontend_accept_referral',{p_id:id});if(act==='start')res=await C.sb.rpc('frontend_start_referral',{p_id:id});if(act==='reject'){const reason=prompt(C.lang==='ar'?'سبب الرفض':'Rejection reason');if(!reason)return;res=await C.sb.rpc('frontend_reject_referral',{p_id:id,p_reason:reason});}if(act==='complete'){const response=prompt(C.lang==='ar'?'رأي الطبيب / الرد النهائي':'Specialist response');if(!response)return;res=await C.sb.rpc('frontend_complete_referral',{p_id:id,p_response:response});}if(res?.error)return C.toast(res.error.message,'error');C.toast(C.lang==='ar'?'تم تحديث التحويل':'Referral updated');C.route('referrals');window.ClinicNotifications?.refresh?.();
  }

  async function showReferral(r,pm,dm){
    const C=Clinic,p=pm.get(r.patient_id)||{},from=dm.get(r.from_doctor_id)||{},to=dm.get(r.to_doctor_id)||{};
    const [visit,diag,inv,med,docs]=await Promise.all([
      C.sb.from('clinical_visits').select('*').eq('id',r.source_visit_id).single(),
      C.sb.from('visit_diagnoses').select('*').eq('visit_id',r.source_visit_id),
      C.sb.from('investigation_orders').select('*').eq('visit_id',r.source_visit_id),
      C.sb.from('visit_prescriptions').select('*').eq('visit_id',r.source_visit_id),
      C.sb.from('clinical_documents').select('*').eq('visit_id',r.source_visit_id).eq('is_voided',false)
    ]);
    const v=visit.data||{};C.showModal({title:C.lang==='ar'?'مراجعة التحويل':'Referral review',wide:true,body:`<div class="referral-review"><div class="detail-grid"><div><span class="field-label">Patient</span><strong>${C.escape(p.english_name||p.arabic_name||'Patient')}</strong></div><div><span class="field-label">From</span><strong>${C.escape(from.display_name||'Doctor')}</strong></div><div><span class="field-label">To</span><strong>${C.escape(to.display_name||'Doctor')}</strong></div><div><span class="field-label">Status</span>${C.statusPill(r.status)}</div></div><div class="callout"><strong>${C.escape(r.referral_reason)}</strong>${r.clinical_question?`<span>${C.escape(r.clinical_question)}</span>`:''}</div><h4>Shared clinical visit</h4><div class="detail-grid"><div class="wide"><span class="field-label">Chief complaint</span><strong>${C.escape(v.chief_complaint||'—')}</strong></div><div class="wide"><span class="field-label">History</span><strong>${C.escape(v.history_present_illness||'—')}</strong></div><div class="wide"><span class="field-label">Examination</span><strong>${C.escape(v.examination||'—')}</strong></div><div class="wide"><span class="field-label">Plan</span><strong>${C.escape(v.treatment_plan||'—')}</strong></div></div><h4>Diagnoses</h4><div class="chips-list">${(diag.data||[]).map(x=>`<span class="info-chip">${C.escape(x.diagnosis_text)}</span>`).join('')||'—'}</div><h4>Investigations</h4><div class="chips-list">${(inv.data||[]).map(x=>`<span class="info-chip">${C.escape(x.investigation_name)}</span>`).join('')||'—'}</div><h4>Medications</h4><div class="chips-list">${(med.data||[]).map(x=>`<span class="info-chip">${C.escape(x.medication_name)} ${C.escape(x.strength||'')}</span>`).join('')||'—'}</div><h4>Documents</h4><div class="stack-list">${(docs.data||[]).map(x=>`<article class="list-card"><span>${C.escape(x.original_file_name)}</span><button class="table-action" data-download-doc="${C.escape(x.storage_path)}">${C.lang==='ar'?'فتح':'Open'}</button></article>`).join('')||'<span class="muted">—</span>'}</div>${r.response?`<div class="callout success-callout"><strong>${C.lang==='ar'?'الرد النهائي':'Final response'}</strong><span>${C.escape(r.response)}</span></div>`:''}</div>`,onOpen:(root)=>{root.querySelectorAll('[data-download-doc]').forEach(btn=>btn.onclick=async()=>{const {data,error}=await C.sb.storage.from('clinical-documents').download(btn.dataset.downloadDoc);if(error)return C.toast(error.message,'error');const url=URL.createObjectURL(data);window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000);});}});
  }
})();
